@baseUrl = http://localhost:7000/api
# @baseUrl = https://nc-accounts.onrender.com/api

### POST a booking
post {{baseUrl}}/bookings
Content-Type: application/json

{
"key": "First key",
"start": "2023-11-14T10:00:00Z",
"startTime": "1699956000000",
"endTime": "1699961400000",
"end": "2023-11-14T11:30:00Z",
"notes": "First Notes",
"consumers_key": "c7f171665c73",
"providers_key": "r3be41",
"services_key": "05451ab7"
}


###
# GET all bookings
get {{baseUrl}}/bookings

###
# GET selected fields from bookings and consumers of a booking id
get {{baseUrl}}/bookings/selected/50620206

###
# GET bookings id
get {{baseUrl}}/bookings/655f4f8a7a0bf99b9357a156

###
# Delete a bookingById
delete {{baseUrl}}/bookings/655f4f8a7a0bf99b9357a156


### POST a consumer
post {{baseUrl}}/consumers
Content-Type: application/json

{
    "consumers_name": "Mike",
    "consumers_pronouns": "He/Him",
    "consumers_email": "mike@hotmail.com",
    "consumers_address_country": "GBR",
    "consumers_key": "txt123GenretedBySetmore",
    "consumers_booking_code": 12345
}

###
# GET all consumers
get {{baseUrl}}/consumers

###
# Delete a consumerById
delete {{baseUrl}}/consumers/655b0a1b7e392f769b5d78a8


### POST a provider
post {{baseUrl}}/providers
Content-Type: application/json

{
    "providers_name": "Mike",
    "providers_email": "mike@hotmail.com",
    "providers_key": "txt123GenretedBySetmore",
    "services_key": ["txt123GenretedBySetmore"]
}

###
# GET all providers
get {{baseUrl}}/providers

###
# Delete a providerById
delete {{baseUrl}}/providers/655d297ef80806902d1ab714

### POST a service
post {{baseUrl}}/services
Content-Type: application/json

{
    "services_duration": 90,
    "services_cost": 0,
    "services_title": "txt123GenretedBySetmore",
    "services_descriptions": "Abcdefghi",
    "services_key": "5451ab7-be63",
    "providers_key": "5451ab7",
    "consumers_key": ["txt123GenretedBySetmore"]
}

###
# GET all services
get {{baseUrl}}/services

###
# Delete a serviceById
delete {{baseUrl}}/services/655d2989f80806902d1ab716
