# @baseUrl = http://localhost:7000/api
@baseUrl = http://localhost:7000/api

### POST a booking
post {{baseUrl}}/bookings
Content-Type: application/json

{"booking":{
"key": "First key",
"start": "2023-11-14T10:00:00Z",
"startTime": "1699956000000",
"endTime": "1699961400000",
"end": "2023-11-14T11:30:00Z",
"notes": "First Notes",
"consumer_key": "c7f171665c73b",
"providers_key": "r3be41",
"services_key": "05451ab7"
}}


###
# GET all bookings
get {{baseUrl}}/bookings

###
# Delete a bookingById
delete {{baseUrl}}/bookings/655b4acbd24e864036251aa0


### POST a consumer
post {{baseUrl}}/consumers
Content-Type: application/json

{"consumer":{
    "consumers_address_country": "GBR",
    "consumers_name": "Mike",
    "consumers_pronouns": "He/Him",
    "consumers_email": "mike@hotmail.com"
}}

###
# GET all consumers
get {{baseUrl}}/consumers

###
# Delete a consumerById
delete {{baseUrl}}/consumers/655b0a1b7e392f769b5d78a8
